name: Main

on:
    schedule:
      - cron: '00 00 * * *'
    push:
        branches: ['main']
    workflow_dispatch:

permissions: write-all

jobs:
  fetch_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch
        run: python leaderboards.py
        env:
            ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
            BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
            DEVICE_ID: ${{ secrets.DEVICE_ID }}
            SECRET: ${{ secrets.SECRET }}

      - name: Commit and push artifact
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Update Leaderboards"
            git push
    